runtime: nodejs10
instance_class: F4
automatic_scaling:
  target_cpu_utilization: 0.85
  min_instances: 1
  max_instances: 1
handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301